env:
  global:
  - CONAN_REFERENCE: "libwebp/next"
  - CONAN_USERNAME: "nunojpg"
  - CONAN_CHANNEL: "ci"
  - CONAN_UPLOAD: "https://api.bintray.com/conan/nunojpg/conan-repo"
  - CONAN_STABLE_BRANCH_PATTERN: "release/*"
  - CONAN_TOTAL_PAGES: 1
  - CONAN_CURRENT_PAGE: 1
matrix:
  include:
  - os: linux
    sudo: required
    language: python
    python: "3.6"
    services:
      - docker
    env: CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
  - os: osx
    osx_image: xcode8.2
    language: generic
    env: PYTHON_VERSION=3.6.1
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
